config/routes.rb
SampleApp::Application.routes.draw do
  resources :post_pictures

  get "spot/index"
  resources :posts

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/spot',    to: 'static_pages#spot',    via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/postup', to: 'posts#new',     via: 'get'

end

app/models/post_picture.rb
class PostPicture < ActiveRecord::Base
  belongs_to :post, :polymorphic => true

  include Rails.application.routes.url_helpers

  mount_uploader :image, ImageUploader

  def to_jq_upload
  {
    "name" => read_attribute(image),
    "url" => image.url,
    "size" => image.size,
    "delete_url" => post_picture_path(:id => id),
    "delete_type" => "DELETE"
  }
  end
end

app/controllers/post_pictures_controller.rb
class PostPicturesController < ApplicationController
  before_action :set_post_picture, only: [:show, :edit, :update, :destroy]

  # GET /post_pictures
  # GET /post_pictures.json
  def index
    @post_pictures = PostPicture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @post_pictures.map{|p| p.to_jq_upload } }
    end

  end

  # GET /post_pictures/1
  # GET /post_pictures/1.json
  def show
    @post_picture = PostPicture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post_picture }
    end
  end

  # GET /post_pictures/new
  def new
    @post_picture = PostPicture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post_picture }
    end
  end

  # GET /post_pictures/1/edit
  def edit
    @post_picture = PostPicture.find(params[:id])
  end

  # POST /post_pictures
  # POST /post_pictures.json
  def create
    @post = Post.find(params[:post_id])
    @post_picture = PostPicture.new(post_picture_params)

    respond_to do |format|
      if @post_picture.save
        #format.html { redirect_to @post_picture, notice: 'Post picture was successfully created.' }
        format.html { render :json => [@post_picture.to_jq_upload].to_json, :content_type => 'text/html', :layout => false }
        #format.json { render action: 'show', status: :created, location: @post_picture }
        format.json { render :json => {files: [@post_picture.to_jq_upload]}, status: :created, location: @post_picture }
      else
        format.html { render action: 'new' }
        format.json { render json: @post_picture.errors, status: :unprocessable_entity }
       #render :json => [{ :error => "custom_failure "}], :status => 304
      end
    end
  end

  # PATCH/PUT /post_pictures/1
  # PATCH/PUT /post_pictures/1.json
  def update
    respond_to do |format|
      if @post_picture.update(post_picture_params)
        format.html { redirect_to @post_picture, notice: 'Post picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post_picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_pictures/1
  # DELETE /post_pictures/1.json
  def destroy
    @post_picture = PostPicture.find(params[:id])
    @post_picture.destroy

#   render :json => true
    respond_to do |format|
      format.html { redirect_to post_pictures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_picture
      @post_picture = PostPicture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_picture_params
      params.require(:post_picture).permit(:post_id, :image)
    end
end

app/helpers/post_pictures_helper.rb
module PostPicturesHelper
end

app/views/post_pictures/_form.html.erb
<%= form_for(@post_picture) do |f| %>
  <% if @post_picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_picture.errors.count, "error") %> prohibited this post_picture from being saved:</h2>

      <ul>
      <% @post_picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_pictures/edit.html.erb
<h1>Editing post_picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_picture %> |
<%= link_to 'Back', post_pictures_path %>

app/views/post_pictures/index.html.erb
<h1>Listing post_pictures</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @post_pictures.each do |post_picture| %>
      <tr>
        <td><%= post_picture.post_id %></td>
        <td><%= post_picture.image %></td>
        <td><%= link_to 'Show', post_picture %></td>
        <td><%= link_to 'Edit', edit_post_picture_path(post_picture) %></td>
        <td><%= link_to 'Destroy', post_picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post picture', new_post_picture_path %>

app/views/post_pictures/new.html.erb
<h1>New post_picture</h1>

<%= render 'form' %>

<%= link_to 'Back', post_pictures_path %>

app/views/post_pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post_picture.post_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @post_picture.image %>
</p>

<%= link_to 'Edit', edit_post_picture_path(@post_picture) %> |
<%= link_to 'Back', post_pictures_path %>