config/routes.rb
SampleApp::Application.routes.draw do
  resources :post_pictures

  get "spot/index"
  resources :posts

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/spot',    to: 'static_pages#spot',    via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/postup', to: 'posts#new',     via: 'get'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	    <span class="user">
		    <%= link_to feed_item.user.name, feed_item.user %>
	    </span>
	    <span class="content"><%= feed_item.content %></span>
	    <span class="timestamp">
		    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	    </span>
		<%= render 'shared/micropost_delete_link', object: feed_item %>
</li>

app/views/shared/_home_no_signed_in.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>
  <h2>
      This is the home page for the
    <a href="http://railstutorial.jp">Ruby on Rails Tutorial</a>
      sample application
  </h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/shared/_home_signed_in.html.erb
<div class="row">
  <div class="span3">
    <section>
    <div>
      <h3>Post Feed(<%= @posts.count %>)</h3>
      <%= render 'shared/post' %>
    </div>
    </section>
    <section>
      <%= link_to "Post up", postup_path, class: "btn btn-large btn-primary" %>
    </section>
  </div>

  <div class="span6">
    <div id="map"></div>
  </div>

  <aside class="span3">
    <section>
    <div>
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
    </section>
    <section>
      <%= render 'shared/user_info' %>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
    <section>
      <%= render 'shared/micropost_form' %>
    </section> 
  </aside>


</div>

  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
  </script>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Compose new micropost..." %>
	</div>
	<%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_post.html.erb
<% if @posts.any? %>
    <ol class="posts">
		<%= render partial: 'shared/post_item', collection: @post_items %>
    </ol>
    <%= will_paginate @post_items %>
<% end %>

app/views/shared/_post_delete_link.html.erb
<% if current_user?(object.user) %>
  <%= link_to "delete", object, method: "delete",
                                   data: { confirm: "You sure?" },
                                   title: object.content %>
<% end %>

app/views/shared/_post_edit_link.html.erb
<% if current_user?(object.user) %>
  <%= link_to "edit", edit_post_path(object) %>
<% end %>

app/views/shared/_post_item.html.erb
<li id="<%= post_item.id %>">
	<%= link_to gravatar_for(post_item.user), post_item.user %>
	    <span class="user">
		    <%= link_to post_item.user.name, post_item.user %>
	    </span>
	    <span class="content"><%= post_item.content %></span>
	    <span class="timestamp">
		    Posted <%= time_ago_in_words(post_item.created_at) %> ago.
	    </span>
        <%= render 'shared/post_delete_link', object: post_item %>
        <%= render 'shared/post_edit_link', object: post_item %>
</li>

app/views/shared/_post_picture_delete_link.html.erb
<%# if current_user?(object.post) %>
	<%= link_to "delete", object, method: "delete" %>
<%# end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_gravatar.html.erb
<a href="<% user_path(user) %>">
  <%= gravatar_for user, size: 52 %>
</a>
<h1>
  <%= user.name %>
</h1>

app/views/shared/_user_info.html.erb
<%= render 'shared/user_gravatar', user: current_user %>
<span>
	<%= link_to "view my profile", current_user %>
</span>
<span>
	<%= pluralize(current_user.microposts.count, "micropost") %>
</span>